package io.github.jframe.exception.core;

import io.github.jframe.exception.HttpException;

import java.io.Serial;

import static org.springframework.http.HttpStatus.NOT_FOUND;

/**
 * Placeholder exception for data not found. These exceptions translate to 404 errors in the controller.
 */
public class DataNotFoundException extends HttpException {

    /** Unique serial id, generated by IntelliJ. */
    @Serial
    private static final long serialVersionUID = 9146345197810622183L;

    /**
     * Constructor.
     */
    public DataNotFoundException(final Exception original) {
        super(original, NOT_FOUND);
    }

    /**
     * Constructor.
     */
    public DataNotFoundException(final String message) {
        super(message, NOT_FOUND);
    }

    /**
     * Constructor.
     */
    public DataNotFoundException(final String message, final Exception original) {
        super(message, original, NOT_FOUND);
    }

}
